import React from 'react';
import { X } from 'lucide-react';

interface TermsOfUseProps {
  isOpen: boolean;
  onClose: () => void;
}

const TermsOfUse: React.FC<TermsOfUseProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-3xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-8">
        <div className="flex items-center justify-between mb-8">
            <h1 className="text-2xl font-bold text-gray-900">Your Skin Care Application</h1>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 transition-colors duration-200 p-2"
            >
              <X size={24} />
            </button>
          </div>

          {/* Content */}
          <div className="prose prose-lg max-w-none text-gray-700">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Terms and Conditions for Your Skin Care Application</h2>
            <p className="text-sm text-gray-500 mb-6">Last Updated: September 4, 2025</p>
            
            <p className="mb-6 leading-relaxed">
              These Terms and Conditions (this "Agreement") is a legal agreement between you ("you" or "user") and Qubitly Ventures ("Company," "we," "us," or "our") for the use of the Your Skin Care application, the associated website, the servers used by the application, the computer files stored on such servers, and all related services, features, and content offered by the Company (collectively, the "Application").
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h3>
            <p className="mb-4 leading-relaxed">
              Please read this Agreement carefully. By creating an account or by accessing or using the Application, you acknowledge that you accept and agree to be bound by the terms of this Agreement. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE APPLICATION.
            </p>
            <p className="mb-6 leading-relaxed">
              We may modify this Agreement from time to time. We will notify you by email, through the Application, or by presenting you with a new version of the Agreement for you to accept if we make modifications that materially change your rights. Your continued use of the Application after the effective date of an updated version of the Agreement will indicate your acceptance of the Agreement as modified.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">2. Medical Services Disclaimer</h3>
            <p className="mb-4 leading-relaxed">
              Your Skin Care application provides informational services only and is not a substitute for professional medical advice.
            </p>
            <p className="mb-4 leading-relaxed">
              The information about health and skincare provided by the Application is not intended to diagnose, treat, cure, or prevent any disease. Products, services, information, and other content provided by the Application, including information linking to third-party websites, are provided for general informational purposes only. The information offered by the Application is not comprehensive and does not cover all skin conditions, diseases, ailments, or their treatments.
            </p>
            <p className="mb-4 leading-relaxed">
              Individuals are different and may react differently to different products or routines. Any recommendations, comments, or insights generated by the Application are based on the data provided and should not be considered as medical claims. The Company is not liable for any information provided by the Application with regard to recommendations for any health purposes. The Company makes no guarantee or warranty with respect to any products or services mentioned.
            </p>
            <p className="mb-6 leading-relaxed">
              Always consult with a dermatologist or other qualified healthcare professional if you have any questions or concerns about your health or skin condition, or if you experience any changes in your condition. If you think you have a medical emergency, call your local emergency number immediately.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">3. Registration and Eligibility</h3>
            <p className="mb-4 leading-relaxed">
              To use the Application, you may be required to create an account ("Account") and will be asked to provide certain personal information. This information will be held and used in accordance with our Privacy Policy. You agree that you will supply accurate and complete information to the Company and that you will update that information promptly after it changes.
            </p>
            <p className="mb-6 leading-relaxed">
              To create an Account and access the Application, you must be at least 13 years old (or 16 years old for residents of the European Union). If you are under the required age, your parent or guardian must review and accept the terms of this Agreement on your behalf.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">4. Subscriptions and Payments</h3>
            <p className="mb-4 leading-relaxed">
              The Application may offer subscriptions that grant you access to premium features and content ("Subscriptions").
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-3">
              <li><strong>Free Trials:</strong> Some Subscriptions may begin with a free trial period. A subscription with a free trial will automatically renew into a paid subscription at the end of the trial period. To avoid being charged, you must cancel the subscription at least 24 hours before the free trial ends.</li>
              <li><strong>Billing:</strong> We offer various subscription options (e.g., monthly, annual). Payment will be charged to your payment method through your App Store Account (e.g., Apple App Store or Google Play Store) after you confirm your purchase.</li>
              <li><strong>Automatic Renewal:</strong> Paid Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current subscription period. Your account will be charged for renewal within 24 hours prior to the end of the current period. You can manage your subscriptions and turn off auto-renewal in your account settings after purchase.</li>
              <li><strong>No Refunds:</strong> All payments made are non-refundable and non-transferable, except as expressly provided in these Terms or as required by law.</li>
            </ul>

            <h3 className="text-xl font-bold text-gray-900 mb-3">5. Your Use of the Application</h3>
            <p className="mb-4 leading-relaxed">
              You are responsible for all of your activity in connection with the Application. As a condition of using the Application, you agree not to use the Application for any purpose that is prohibited by this Agreement. You shall not:
            </p>
            <ol className="list-lower-alpha pl-6 mb-6 space-y-2">
              <li>Resell, rent, lease, loan, sublicense, distribute, or otherwise transfer rights to the Application.</li>
              <li>Modify, reverse engineer, decompile or disassemble the Application.</li>
              <li>Copy, adapt, alter, modify, translate, or create derivative works of the Application without written authorization from the Company.</li>
              <li>Permit other individuals to use the Application via a shared network connection, except under the terms of this Agreement.</li>
              <li>Circumvent or disable any technological features in the Application for protection of intellectual property rights.</li>
              <li>Use the Application to compile data in a manner that is used or usable by a competitive product or service.</li>
              <li>Use your Account to advertise, solicit, or transmit any commercial advertisements, including junk e-mail or repetitive messages.</li>
              <li>Use your Account to engage in any illegal conduct.</li>
              <li>Upload to transmit any communications that infringe or violate the rights of any party.</li>
              <li>Upload media of any kind that contains expressions of hate, abuse, offensive images or conduct, obscenity, pornography, sexually explicit material, or any material that could give rise to any civil or criminal liability under applicable law.</li>
              <li>Upload any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or this website.</li>
            </ol>
            <p className="mb-6 leading-relaxed">
              Any such forbidden use shall immediately terminate your license to use the Application.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">6. User Content</h3>
            <p className="mb-6 leading-relaxed">
              You may be able to submit photos and other information ("User Content") to the Application. You retain all rights in, and are solely responsible for, the User Content you post. By posting User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, process, reproduce, and display such User Content solely for the purpose of operating and improving the Application.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">7. Intellectual Property and Limited License</h3>
            <p className="mb-4 leading-relaxed">
              We grant you a personal, worldwide, revocable, non-transferable, and non-exclusive license to access and use the Application for personal and non-commercial purposes in accordance with this Agreement.
            </p>
            <p className="mb-6 leading-relaxed">
              All content, features, and functionality of the Application, including but not limited to text, graphics, logos, and software, are the exclusive property of Your Skin Care application and its licensors and are protected by international copyright, trademark, and other intellectual property laws. All rights, title, and interest in and to the Application not expressly granted in this Agreement are reserved by the Company.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">8. Warranty Disclaimer</h3>
            <p className="mb-6 leading-relaxed uppercase text-sm">
              THE APPLICATION IS PROVIDED "AS IS" AND "AS AVAILABLE" AND IS PROVIDED WITHOUT ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. THE COMPANY, AND ITS DIRECTORS, EMPLOYEES, AGENTS, AND PARTNERS DO NOT WARRANT THAT: (A) THE APPLICATION WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (C) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE APPLICATION IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE APPLICATION WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE APPLICATION IS SOLELY AT YOUR OWN RISK.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">9. Limitation of Liability</h3>
            <p className="mb-6 leading-relaxed uppercase text-sm">
              IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, AGENTS, OR EMPLOYEES BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS, OR LOSS OF DATA) ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THIS APPLICATION. IN NO EVENT WILL THE COMPANY'S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE APPLICATION EXCEED THE AMOUNTS YOU HAVE PAID TO THE COMPANY FOR USE OF THE APPLICATION OR ONE HUNDRED DOLLARS ($100) IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO THE COMPANY, AS APPLICABLE. THE COMPANY IS NOT LIABLE FOR ANY PERSONAL INJURY, INCLUDING DEATH, CAUSED BY YOUR USE OR MISUSE OF THE APPLICATION.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">10. Indemnity</h3>
            <p className="mb-6 leading-relaxed">
              You agree to defend, indemnify, and hold the Company, its officers, directors, employees, and agents harmless from and against any claims, actions or demands, liabilities, and settlements including without limitation, reasonable legal fees, resulting from, or alleged to result from, your violation of this Agreement.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">11. Termination</h3>
            <p className="mb-6 leading-relaxed">
              We may terminate or suspend your access to the Application at any time, without prior notice or liability, for any reason, including if you breach this Agreement.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">12. Miscellaneous</h3>
            <p className="mb-6 leading-relaxed">
              This Agreement shall be governed by the laws of the State of Delaware, USA, without regard to its conflict of law provisions. Sole and exclusive jurisdiction for any action or proceeding arising out of or related to this Agreement shall be in the State of Delaware. If any provision of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, such provision shall be eliminated or limited to the minimum extent necessary, and the remaining provisions of this Agreement will continue in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mb-3">13. Contact Us</h3>
            <p className="mb-6 leading-relaxed">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mb-6 leading-relaxed font-semibold">
              care@yourskincaredotcom
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfUse;
